# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_pub_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.TimeField(null=True),
        ),
    ]
