# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180211_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMDB_CI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=255)),
                ('AssetStatus', models.CharField(max_length=255)),
                ('Environment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CMDB_CI_IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE', models.CharField(max_length=32)),
                ('cmdb_ci', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.CMDB_CI')),
            ],
        ),
        migrations.CreateModel(
            name='CMDB_CI_SW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE', models.CharField(max_length=32)),
                ('cmdb_ci', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.CMDB_CI')),
            ],
        ),
    ]
