# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_cmdb_ci_cmdb_ci_ip_cmdb_ci_sw'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMDB_CI_SOFT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE', models.CharField(max_length=32)),
                ('OS_Type', models.CharField(choices=[('WINDOWS', 'WINDOWS'), ('LINUX', 'LINUX'), ('ESX', 'ESX')], default='WINDOWS', max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='cmdb_ci_sw',
            name='cmdb_ci',
        ),
        migrations.RemoveField(
            model_name='cmdb_ci',
            name='AssetStatus',
        ),
        migrations.RemoveField(
            model_name='cmdb_ci',
            name='Environment',
        ),
        migrations.RemoveField(
            model_name='cmdb_ci_ip',
            name='TYPE',
        ),
        migrations.AddField(
            model_name='cmdb_ci',
            name='Alias',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cmdb_ci',
            name='Asset_Status',
            field=models.CharField(choices=[('Decommissioned', 'decommissioned'), ('Deactive', 'deactive'), ('Active', 'active'), ('Implementing', 'implementing'), ('Not owned by DXC', 'not owned by DXC')], default='Decommissioned', max_length=255),
        ),
        migrations.AddField(
            model_name='cmdb_ci_ip',
            name='Network_Zone',
            field=models.CharField(choices=[('Infra zone', 'Infra zone'), ('APP/DB zone', 'APP/DB zone'), ('Web zone', 'Web zone')], default='Infra zone', max_length=32),
        ),
        migrations.AlterField(
            model_name='cmdb_ci_ip',
            name='cmdb_ci',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.CMDB_CI'),
        ),
        migrations.DeleteModel(
            name='CMDB_CI_SW',
        ),
        migrations.AddField(
            model_name='cmdb_ci_soft',
            name='cmdb_ci',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.CMDB_CI'),
        ),
    ]
