# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180228_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmdbCi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=255)),
                ('Asset_Status', models.IntegerField(choices=[(1, 'Decommissioned'), (2, 'Deactive'), (3, 'Active'), (4, 'Implementing'), (5, 'Not owned by DXC')], default=1)),
                ('Alias', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'cmdb_ci',
            },
        ),
        migrations.CreateModel(
            name='CmdbCiIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Network_Zone', models.IntegerField(choices=[(1, 'Infra zone'), (2, 'APP/DB zone'), (3, 'Web zone')], default=1)),
                ('cmdb_ci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.CmdbCi')),
            ],
            options={
                'db_table': 'cmdb_ci_ip',
            },
        ),
        migrations.CreateModel(
            name='CmdbCiSoft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE', models.CharField(max_length=32)),
                ('OS_Type', models.IntegerField(choices=[(1, 'WINDOWS'), (2, 'LINUX'), (3, 'ESX')], default=1)),
                ('cmdb_ci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.CmdbCi')),
            ],
            options={
                'db_table': 'cmdb_ci_soft',
            },
        ),
        migrations.RemoveField(
            model_name='cmdb_ci_ip',
            name='cmdb_ci',
        ),
        migrations.RemoveField(
            model_name='cmdb_ci_soft',
            name='cmdb_ci',
        ),
        migrations.DeleteModel(
            name='CMDB_CI',
        ),
        migrations.DeleteModel(
            name='CMDB_CI_IP',
        ),
        migrations.DeleteModel(
            name='CMDB_CI_SOFT',
        ),
    ]
