# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180301_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdbcisoft',
            name='TYPE',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
