# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180612_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TestC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TestB',
            fields=[
                ('testa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.TestA')),
                ('desc', models.CharField(default='', max_length=32)),
            ],
            bases=('blog.testa',),
        ),
        migrations.AddField(
            model_name='testc',
            name='test_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to='blog.TestA'),
        ),
    ]
